/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ubeauty.View;

/**
 *
 * @author Eduardo Buzzi
 */
public class PanelAgendamento extends javax.swing.JPanel {

    /**
     * Creates new form teste2
     */
    public PanelAgendamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLogo = new javax.swing.JLabel();
        btnEstabelecimentos = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JLabel();
        txtEstabelecimento = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtServico = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtHorario = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPagamento = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnSolicitarAlteracao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelarAgendamento = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seu agendamento");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, 60));

        btnLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        add(btnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 30));

        btnEstabelecimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/area-titulo.png"))); // NOI18N
        add(btnEstabelecimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, -1));

        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btn-voltar-escuro.png"))); // NOI18N
        add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        txtEstabelecimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEstabelecimento.setForeground(new java.awt.Color(58, 22, 46));
        txtEstabelecimento.setText("*nome*");
        add(txtEstabelecimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(58, 22, 46));
        jLabel18.setText("Estabelecimento:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 30));

        txtServico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtServico.setForeground(new java.awt.Color(58, 22, 46));
        txtServico.setText("*serviço*");
        add(txtServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 30));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(58, 22, 46));
        jLabel19.setText("Serviço:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, 30));

        txtPreco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPreco.setForeground(new java.awt.Color(58, 22, 46));
        txtPreco.setText("R$00,00");
        add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 30));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(58, 22, 46));
        jLabel20.setText("Preço:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 30));

        txtHorario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHorario.setForeground(new java.awt.Color(58, 22, 46));
        txtHorario.setText("00/00/0000 - 00:00");
        add(txtHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, 30));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(58, 22, 46));
        jLabel21.setText("Data/hora:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, 30));

        txtPagamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPagamento.setForeground(new java.awt.Color(58, 22, 46));
        txtPagamento.setText("Aplicativo (pago)");
        add(txtPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 280, 30));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(58, 22, 46));
        jLabel22.setText("Cancelar agendamento?");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 280, 30));

        btnSolicitarAlteracao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnSolicitarAlteracao.setForeground(new java.awt.Color(255, 255, 255));
        btnSolicitarAlteracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSolicitarAlteracao.setText("Solicitar");
        btnSolicitarAlteracao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSolicitarAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSolicitarAlteracaoMousePressed(evt);
            }
        });
        add(btnSolicitarAlteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 110, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-rosa.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 110, 50));

        btnCancelarAgendamento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelarAgendamento.setForeground(new java.awt.Color(255, 102, 153));
        btnCancelarAgendamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarAgendamento.setText("CANCELAR");
        btnCancelarAgendamento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarAgendamentoMousePressed(evt);
            }
        });
        add(btnCancelarAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 120, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-rosa-outline.png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 130, 50));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(58, 22, 46));
        jLabel23.setText("Forma de Pagamento:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 280, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(58, 22, 46));
        jLabel24.setText("Solicitar alteração?");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 280, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarAlteracaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSolicitarAlteracaoMousePressed
        System.out.println("ok");
    }//GEN-LAST:event_btnSolicitarAlteracaoMousePressed

    private void btnCancelarAgendamentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarAgendamentoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarAgendamentoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancelarAgendamento;
    private javax.swing.JLabel btnEstabelecimentos;
    private javax.swing.JLabel btnLogo;
    private javax.swing.JLabel btnSolicitarAlteracao;
    private javax.swing.JLabel btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txtEstabelecimento;
    private javax.swing.JLabel txtHorario;
    private javax.swing.JLabel txtPagamento;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtServico;
    // End of variables declaration//GEN-END:variables
}
