/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ubeauty.View;

import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Eduardo Buzzi
 */
public class TelaPrincipal extends javax.swing.JFrame {

    CardLayout cl = new CardLayout();
    JPanel jp = new PanelPrincipal();
    JPanel jp2 = new PanelNotificacoes();
    JPanel jp3 = new PanelPaginaSalao();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);

        ImageIcon icon = new ImageIcon(this.getClass().getResource("/icon.png"));
        setIconImage(icon.getImage());

        painelConteudo.setLayout(cl);
        painelConteudo.add(jp, "inicial");
        painelConteudo.add(jp2, "notif");
        painelConteudo.add(jp3, "paginasalao");
        cl.show(painelConteudo, "paginasalao");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNotificacoes = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JLabel();
        btnMensagens = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelConteudo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNotificacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-notif.png"))); // NOI18N
        getContentPane().add(btnNotificacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 30, 30));

        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-home.png"))); // NOI18N
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 30, 30));

        btnUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-usuario.png"))); // NOI18N
        getContentPane().add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 30, 30));

        btnMensagens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMensagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botao-msg.png"))); // NOI18N
        getContentPane().add(btnMensagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barra-branca.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 320, 100));

        painelConteudo.setLayout(new java.awt.CardLayout());
        getContentPane().add(painelConteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnMensagens;
    private javax.swing.JLabel btnNotificacoes;
    private javax.swing.JLabel btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel painelConteudo;
    // End of variables declaration//GEN-END:variables
}
